USE [master]
GO
/****** 对象:  Database [QPPlatformManagerDB]    脚本日期: 04/25/2011 17:01:53 ******/
CREATE DATABASE [QPPlatformManagerDB] ON  PRIMARY 
( NAME = N'QPPlatformManagerDB', FILENAME = N'D:\数据库\QPPlatformManagerDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'QPPlatformManagerDB_log', FILENAME = N'D:\数据库\QPPlatformManagerDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'QPPlatformManagerDB', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QPPlatformManagerDB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [QPPlatformManagerDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [QPPlatformManagerDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QPPlatformManagerDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QPPlatformManagerDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QPPlatformManagerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QPPlatformManagerDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QPPlatformManagerDB] SET  READ_WRITE 
GO
ALTER DATABASE [QPPlatformManagerDB] SET RECOVERY FULL 
GO
ALTER DATABASE [QPPlatformManagerDB] SET  MULTI_USER 
GO
ALTER DATABASE [QPPlatformManagerDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QPPlatformManagerDB] SET DB_CHAINING OFF 