//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GameClient.rc
//
#define IDR_MAINFRAME                   128
#define IDR_WAVE1                       146
#define IDB_VIEW_BACK                   147
#define IDB_VIEW_FILL                   148
#define IDB_GAME_CARD                   149
#define IDB_JETTOM_VIEW                 150
#define IDB_SCORE_NUMBER                151
#define IDB_BT_JETTON_1000              152
#define IDB_BT_JETTON_10000             153
#define IDB_BT_JETTON_1                 154
#define IDB_BT_JETTON_10                155
#define IDB_BT_JETTON_100               156
#define IDB_BT_JETTON_100000            157
#define IDB_FRAME_R                     159
#define IDB_FRAME_L                     160
#define IDB_FRAME_M                     161
#define IDB_WIN_FLAGS                   162
#define IDC_SCORE_1                     163
#define IDC_SCORE_10                    164
#define IDC_SCORE_100000                165
#define IDC_SCORE_10000                 166
#define IDC_SCORE_1000                  167
#define IDC_SCORE_100                   168
#define IDR_WAVE2                       174
#define IDD_DLG_GAME_RECORD             177
#define IDB_BT_APPLY_BANKER             179
#define IDB_BITMAP2                     180
#define IDB_BT_CANCEL_BANKER            180
#define IDB_BITMAP1                     183
#define IDC_SCORE_500                   187
#define IDC_SCORE_1000000               187
#define IDC_SCORE_50000                 188
#define IDC_SCORE_5000000               188
#define IDB_BT_SCORE_MOVE_L             190
#define IDB_BT_SCORE_MOVE_R             191
#define IDB_APPLY_USER_BACK             193
#define IDB_FRAME_OLD_PING_JIA          200
#define IDB_FRAME_OLD_TONG_DIAN_PING    201
#define IDB_FRAME_OLD_XIAN_JIA          202
#define IDB_FRAME_OLD_XIAN_TIAN_WANG    203
#define IDB_FRAME_OLD_ZHUANG_JIA        204
#define IDB_FRAME_OLD_ZHUANG_TIAN_WANG  205
#define IDB_GAME_END                    206
#define IDB_GAME_END_FRAME              207
#define IDB_GAME_POINT                  208
#define IDB_CHANGE_BANKER               209
#define IDB_ME_BANKER                   210
#define IDB_NO_BANKER                   211
#define IDB_BT_CANCEL_APPLY             212
#define IDB_TIME_FLAG                   213
#define IDB_ME_SCORE_NUMBER             214
#define IDB_BT_CHART                    217
#define IDD_VIEW_CHART                  218
#define IDB_CHART_BACK                  219
#define IDB_BT_CHART_CLOSE              220
#define IDR_PNG2                        226
#define IDB_BT_JETTON_1000000           227
#define IDB_BT_JETTON_5000000           228
#define IDR_PNG1                        229
#define IDR_PNG3                        230
#define IDB_K_22_26                     231
#define IDB_K_2_6                       232
#define IDB_K_2_13                      233
#define IDB_K_17_21                     234
#define IDB_K_15_26                     235
#define IDB_K_14                        236
#define IDB_K_12_16                     237
#define IDB_K_LONG                      238
#define IDB_K_HE                        239
#define IDB_K_HU                        240
#define IDB_K_7_11                      241
#define IDB_BITMAP3                     245
#define IDB_BITMAP4                     246
#define IDD_DIALOG_SYSTEM               247
#define IDB_GETGOLD						248
#define IDB_SAVEGOLD					249
#define IDB_CLOSE						250
#define IDB_BT_FRESH					251
#define STATICEDIT2                     1001
#define STATICEDIT1                     1002
#define STATICEDIT3                     1003
#define STATICEDIT                      1004
#define IDC_COMBO_TIMES                 1013
#define IDC_BUTTON_RESET                1025
#define IDC_BUTTON_SYN                  1026
#define IDC_BUTTON_OK                   1027
#define IDC_BUTTON_CANCEL               1028
#define IDC_STATIC_TIMES                1029
#define IDC_STATIC_AREA                 1030
#define IDC_STATIC_NOTIC                1031
#define IDC_STATIC_TEXT                 1032
#define IDC_STATIC_INFO                 1033
#define IDC_CHECK_LONG                  1034
#define IDC_CHECK_PING                  1035
#define IDC_CHECK_HU                    1036
#define IDC_CHECK_2_13                  1037
#define IDC_CHECK_15_26                 1038
#define IDC_CHECK_14                    1039
#define IDC_CHECK_7_11                  1040
#define IDC_CHECK_17_21                 1041
#define IDC_CHECK_12_16                 1042
#define IDC_CHECK10                     1043
#define IDC_CHECK_22_26                 1043
#define IDC_CHECK_2_6                   1044
#define IDC_RECORD_LIST                 1056
#define IDB_BT_DRAW                     2000
#define IDB_BT_STORAGE                  2001
#define IDC_IN_COUNT                    2002
#define IDC_BANK_DRAW                   2003
#define IDC_GAME_GOLD                   2004
#define IDC_STATIC_PASS                 2005
#define IDC_BANK_STORAGE                2006
#define IDD_BANK_STORAGE                2007
#define IDC_STORAGE_GOLD                2008
#define IDC_USER_PASSWORD               2009
#define IDC_CHECK_ALL                   2010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        256
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
