USE [master]
GO
/****** 对象:  Database [QPGameMatchDB]    脚本日期: 12/08/2008 11:31:04 ******/
CREATE DATABASE [QPGameMatchDB] ON  PRIMARY 
( NAME = N'QPGameMatchDB', FILENAME = N'D:\数据库\QPGameMatchDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'QPGameMatchDB_log', FILENAME = N'D:\数据库\QPGameMatchDB_log.LDF' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 COLLATE Chinese_PRC_CI_AS
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QPGameMatchDB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [QPGameMatchDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [QPGameMatchDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QPGameMatchDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QPGameMatchDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QPGameMatchDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QPGameMatchDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QPGameMatchDB] SET  READ_WRITE 
GO
ALTER DATABASE [QPGameMatchDB] SET RECOVERY FULL 
GO
ALTER DATABASE [QPGameMatchDB] SET  MULTI_USER 
GO
ALTER DATABASE [QPGameMatchDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QPGameMatchDB] SET DB_CHAINING OFF 

if ( ((@@microsoftversion / power(2, 24) = 8) and (@@microsoftversion & 0xffff >= 760)) or 
		(@@microsoftversion / power(2, 24) >= 9) )begin 
	exec dbo.sp_dboption @dbname =  N'QPGameMatchDB', @optname = 'db chaining', @optvalue = 'OFF'
 end